	<div  class="widget" >
		<div class="row">
			<div class="columns small-12">
				<div class="title"><h3>Locations</h3>
				</div>
			</div>
			
		<div class="row editable" id="bottomLocations">
			<div class="columns large-4">
		
		<h5>Denver, Colorado</h5>
		9239 Brighton Rd., Unit #201<br>
		Henderson CO 80640<br>
		<b>(303) 558-3152</b><br><br>
		<a class="small button btn-style-1" href="/denver-colorado.php">More Info</a>
		
			</div>
			<div class="columns large-4">
		
		<h5>Las Vegas, Nevada</h5>
		4020 E. Lone Mountain Rd.<br>
		North Las Vegas, NV 89081<br>
		<b>(702) 623-3434</b><br><br>
		<a class="small button btn-style-1" href="/las-vegas-nevada.php">More Info</a>
		
			</div>
			<div class="columns large-4">
		
		<h5>Phoenix, Arizona</h5>
		440 S. 54th Ave.<br>
		Phoenix, AZ 85043<br>
		<b>(602) 457-3294</b><br><br>
		<a class="small button btn-style-1" href="/phoenix-arizona.php">More Info</a>
		
			</div></div>
	 
	 </div>