 <!-- Start:Footer-->
 		 <footer>
 		 	
 		 	<div class="row widgets-block"> 		 		
 		 		
 		 		<div class="editable small-6 large-4 column widget" id="included-region-1"><h4>Campus Locations</h4>
<ul class="link-list">
<li><a href="phoenix-arizona.php">Phoenix, AZ</a></li>
<li><a href="las-vegas-nevada.php">Las Vegas, NV</a></li>
<li><a href="denver-colorado.php">Denver, CO</a></li>
</ul>
<h4>Extra Info</h4>
<ul class="link-list">
<li><a href="Consumer-Guide-2015.pdf" target="_blank">Consumer Information</a></li>
<li><a href="financial-aid.php">Financial Aid</a></li>
<li><a href="gainful-employment.php">Gainful Employment</a></li>
<li><a href="NetPriceCalculator/npcalc.htm" target="_blank">Net Price Calculator</a></li>
<li><a href="migration/Code_of_Conduct_2012.pdf">Code of Conduct</a></li>
</ul></div>
			   
			  <div class="editable small-6 large-4 column widget" id="included-region-2"><p><img style="width: 40%;" src="img/logo-website-white.png" alt=""></p>
<h4>AIT Truck Driver Training</h4>
<p>440 S 54th Ave<br> Phoenix, AZ 85043<br> <i class="icon-phone"></i>(602) 233-1898</p></div>
			   
			   <div class="small-12 large-4 column widget">
	               <h4 class="title">Recent Blog Articles</h4>
	               <div class="feedgrabbr_widget" id="fgid_665e398ef607440471a4b44c9"></div>
<script> if (typeof(fg_widgets)==="undefined") fg_widgets = new Array();fg_widgets.push("fgid_665e398ef607440471a4b44c9");</script>
<script src="http://www.feedgrabbr.com/widget/fgwidget.js"></script>

 
                </div> 
 		 	</div>
 		 	
 		 	<div id="social-links" class="aligncenter">
 		 		<a href="" class="up-arrow"><i class="icon-angle-up"></i></a>
 		 		<div class="row">
 		 			<a href="https://www.facebook.com/AIT-Truck-Driver-Training-1109915452368609/?fref=ts" target="_blank"><i class="icon-facebook icon-circled icon-64"></i></a>
 		 			<a href="https://twitter.com/AITSchools" target="_blank"><i class="icon-twitter icon-circled icon-64"></i></a>
 		 		</div>
 		
				 
			</div>
			
			</div>
 		 	
 		 				<div class="row hide-for-small" id="icon-list">
		 		 <div class="columns small-12">
			 		 
			 		 <ul class="small-block-grid-17 large-block-grid-7">
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-cvta-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-accsc-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-ptdi-135x110.jpg" alt=""></a></li>
	 		 	        <li><a href="#"><img class="logo-icon" src="/migration/WIA-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/BBB-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/tca-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/apscu-135x110.jpg" alt=""></a></li>
	             </ul>
	                               
		 		 	</div>      
	 		 </div>
 		 	
 		 </footer>
 		   <!-- End:Footer-->