  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0" />  
  <link href='https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,300,600|Oswald:400,300' rel='stylesheet' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <!--[if IE 7]>
		  <link rel="stylesheet" href="css/font-awesome-ie7.min.css">
  <![endif]-->
  <link rel="stylesheet" href="/css/style.css" media="all"/>
  