
 		 				<div class="row" id="icon-list">
		 		 <div class="columns small-12">
			 		 
			 		 <ul class="small-block-grid-7 large-block-grid-8">
	 		 			<li> <a href="#"><img class="logo-icon" src="/migration/logo-adot-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-cvta-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-accsc-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/logo-ptdi-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/NVDMV-135x110.jpg" alt=""></a></li>
	 		 	        <li><a href="#"><img class="logo-icon" src="/migration/WIA-135x110.jpg" alt=""></a></li>
                        <li><a href="#"><img class="logo-icon" src="/migration/coDMV-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/BBB-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/ATA-135x110.jpg" alt=""></a></li>
                         <li><a href="#"><img class="logo-icon" src="/migration/APSA-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/ADVS-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/tca-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/nta-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/caccs-135x110.jpg" alt=""></a></li>
	                     <li><a href="#"><img class="logo-icon" src="/migration/apscu-135x110.jpg" alt=""></a></li>
	             </ul>
	                               
		 		 	</div>      
	 		 </div>
