<nav class="top-bar" >
<ul class="title-area"> 
		<li class="name">
        <h1><a href="index.php"><img class="logo" src="/img/logo-website-white.png"></a></h1>
    </li>
    <li id="menu-icon" class="toggle-topbar"><a href="#">Menu <i class="icon-reorder"></i></a></li>
</ul> 
<section class="top-bar-section"> 
        <ul class="right">
	        <li><a href="index.php">Home</a></li>
	        
	        <li class="has-dropdown"><a href="cdl-course-information.php" >Courses</a>
		      <ul class="dropdown">
		           <li><a href="/truck-driver-training-course.php">Truck Driver Training Course</a></li>
		       	   <li><a href="/diesel-truck-driver-training.php">Diesel Truck Driver Training</a></li>
		       	   <li><a href="/commercial-truck-driver-training.php">Commercial Truck Driver Training</a></li>
		        	<li><a href="/professional-truck-driver-training.php">Professional Truck Driver Training</a></li>
		        	<li><a href="/faq.php">FAQ</a></li>
		        </ul> 
			</li>
			
		 <li class="has-dropdown"><a href="/job-placement.php">Job Placement</a>
		      <ul class="dropdown">
		           <li><a href="/carriers.php">Preferred Carriers</a></li>
		        	<li><a href="/careers-in-trucking.php">Careers in Trucking</a></li>
		        	<li><a href="/the-need.php">The US Needs Drivers</a></li>
		        	<li><a href="/trucking-industry.php">About the Industry</a></li>
		        	<li><a href="/pay-benefits.php">Driver Pay & Benefits</a></li>
		        </ul> 
			</li>
			
			<li class="has-dropdown"> <a href="/learn-about-ait-cdl-schools.php" >About</a>
		      <ul  class="dropdown">
		        	<li><a href="/our-mission.php">Mission</a></li>
		        	<li><a href="/history.php">History</a></li>
		        	<li><a href="/recognition.php">Recognition</a></li>
		        	<li><a href="/accreditation.php">Accreditation</a></li>
		        	<li><a href="/picking-a-cdl-school.php">Picking a School</a></li>
		        </ul> 
			</li>
			
			<li class="has-dropdown"> <a href="/financial-aid.php" >Financial Aid</a>
		      <ul  class="dropdown">
		            <li><a href="/grants-and-aid.php">Grants & Aid</a></li>
		        	<li><a href="/tuition-reimbursement.php">Reimbursement</a></li>
		        	<li><a href="/military.php">Military Programs</a></li>
		        	<li><a href="/financing.php">Financing CDL Training</a></li>
		        </ul> 
			</li>
			
			<li><a href="/blog" target="_blank">Blog</a></li>
			
			<li class="has-dropdown"><a href="/locations.php">Locations</a> 
		      <ul  class="dropdown">
		        	<li></li>
		        	<li><a href="/phoenix-arizona.php">Phoenix, AZ</a></li>
		        	<li><a href="/denver-colorado.php">Denver, CO</a></li>
		        	<li><a href="/las-vegas-nevada.php">Las Vegas, NV</a></li>
		        </ul> 
			</li>
		<span><a class="radius success large applynow button hide-for-small" href="/contact-ait-trucking-school.php" >Apply Now</a><span>
		
		<li class="active show-for-small"><a href="/contact-ait-trucking-school.php">Apply Now</a></li>
		
        </ul> 
</section>
</nav>