	<div  class="editable widget" id="Locations"><div class="title">
<h3>Locations</h3>
</div>
<h5>Denver, Colorado</h5>
<p>9239 Brighton Rd., Unit #201<br> Henderson CO 80640<br> <b>(303) 558-4505</b><br><br> <a class="small button btn-style-1" href="denver-colorado.php">More Info</a></p>
<hr>
<h5>Las Vegas, Nevada</h5>
<p>4020 E. Lone Mountain Rd.<br> North Las Vegas, NV 89081<br> <b>(702) 644-0155</b><br><br> <a class="small button btn-style-1" href="las-vegas-nevada.php">More Info</a></p>
<hr>
<h5>Phoenix, Arizona</h5>
<p>440 S. 54th Ave.<br> Phoenix, AZ 85043<br> <b>(602) 233-1898</b><br><br> <a class="small button btn-style-1" href="phoenix-arizona.php">More Info</a></p></div>