 <div class="widget" id="SectionLinks">
		<div class="title"><h3>Extra Info</h3></div>
		<ul>
			<li><a href="/migration/Consumer-Guide-2014.pdf">Consumer Information</a></li>
			<li><a href="financial-aid.php">Financial Aid</a></li>
			<li><a href="gainful-employment.php">Gainful Employment</a></li>
			<li><a href="/NetPriceCalculator/npcalc.htm">Net Price Calculator</a></li>
			<li><a href="/migration/Code_of_Conduct_2012.pdf">Code of Conduct</a></li>
		</ul>
	 </div>
